### ISSUE TITLE
Mourning queen spawn

### ISSUE THREAD

**Issue by goodete** [thedefside/journey_to_valhalla#2]
Mourning Queen raid spawned at night in the Meadows at my little house.  Very early game, have only beaten first boss. have not even gotten bronze yet.

**Comment by goodete** [comment]
Update: raid doesn't end.  Dark elves don't De-spawn.  Logging out of game completely does not reset adds or raid.  Adds chased to world spawn stones, in a perpetual state of instant dying at Spawn stones.

**Comment by thedefside** [comment]
I'm really sorry this happened to you. It also happened to me, but I was wearing top tier gear and weapons. This event was broken and would never happen previously, but it looks like I have messed something up because it should not happen in the meadows, and should not happen until you have defeated Yagluth. I'll work on getting it fixed in the next update. For now, you can go to the BepInEx/config/JTV/Mistlands folder and delete all the rrrmonsters.custom.Svartalfr files. That should remove the Dark Elves from your game, and you should be able to continue playing. Again, sorry for the trouble.

**Comment by thedefside** [comment]
The Mourning Queen now only spawns when you summon her from an altar.
